version: "3.8"
services:
  blockbookznz:
    build: .
    container_name: znz_blockbook
    volumes:
      - ./blockbook/znz:/opt/coins/blockbook/znz
      - ./blockbook/db:/opt/coins/data/znz/blockbook/db
      - ./backend:/opt/coins/data/znz/
    ports:
      - 9013:9013
      - 9113:9113
      - 8022:8022
networks: {}
